### PR TITLE
Add support for 4.10

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by olafhering** [comment]
Is this supposed to work on 4.05? After upgrading from cf49ec820afe1670a7ca870970ec1764201e1207..5efccc2c8b0f33564763d7f3394a0b0cc154f5cd build fails:

````
[   31s] Command [189] exited with code 2:
[   31s] $ (cd _build/default && /usr/bin/ocamlc.opt -w -40 -g -bin-annot -I src/.migrate_parsetree.objs/byte -I /usr/lib64/ocaml/compiler-libs -I /usr/lib64/ocaml/ppx_derivers -I /usr/lib64/ocaml/result -no-alias-deps -open Migrate_parsetree__ -o src/.migrate_parsetree.objs/byte/migrate_parsetree__Migrate_parsetree_409_410_migrate.cmo -c -impl src/migrate_parsetree_409_410_migrate.pp.ml)
[   31s] File "src/migrate_parsetree_409_410_migrate.ml", line 22, characters 18-28:
[   31s] Error: Unbound module Option
````

**Comment by ghost** [comment]
Indeed. It's now fixed in master
