### ISSUE TITLE
ocaml-migrate-parsetree.1.7.1 breaks any program using Option

### ISSUE THREAD

**Issue by talex5** [let-def/migrate-parsetree#93]
It appears that ocaml-migrate-parsetree 1.7.1 added a new, top-level (non-wrapped) `Option` module. This breaks anything using the stdlib's option module. Example program:

```ocaml
let iter = Option.iter
```

and `dune` file:

```
(executable
 (name main)
 (libraries ocaml-migrate-parsetree))
```

This fails with:

```
File "main.ml", line 1, characters 8-19:
1 | let x = Option.iter
            ^^^^^^^^^^^
Error (alert deprecated): module Option
Access modules via the Migrate_parsetree toplevel module. Use Migrate_parsetree.Option instead.
File "main.ml", line 1, characters 8-19:
1 | let x = Option.iter
            ^^^^^^^^^^^
Error: Unbound value Option.iter
```

If the `ocaml-migrate-parsetree` dependency is removed, it works.

(seen in https://github.com/ocaml/opam-repository/issues/16216)

**Comment by avsm** [comment]
Introduced in https://github.com/ocaml-ppx/ocaml-migrate-parsetree/commit/3213780730a7c058199ad75e73ff5b05afa23465

**Comment by yzh119** [comment]
Hi @talex5 , any ideas on how to fix this if I use `Option.***` in my program?

**Comment by ghost** [comment]
Fixed and released in 1.7.2

**Comment by yzh119** [comment]
Thanks~
